title: Syntax & Scribbles

description: A quirky mashup of tech notes, random thoughts, and whatever else spills out of my brain.

theme: minima

header_pages:
  - about.md
  - contact.md

show_excerpts: true
page_excerpts: true

minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/jekyll/jekyll" }

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
