# Site settings
title: "Syntax & Scribbles"

description: "A quirky mashup of tech notes, random thoughts, and whatever else spills out of my brain."

theme: "minima"

# Site settings
email: "my_email@email.com"
author: "Barry Weiss"


# Only pages listed here will be shown in the header
# header_pages:
#   - about.md
#   - contact.md
#   - resources.md

# Social media links
linkedin_username: bweiss
github_username: barweiss45



show_excerpts: true
page_excerpts: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
