title: Syntax & Scribbles

description: A quirky mashup of tech notes, random thoughts, and whatever else spills out of my brain.

theme: minima

# Only pages listed here will be shown in the header
# header_pages:
#   - about.md
#   - contact.md
#   - resources.md

linkedin_username: bweiss
github_username: barweiss45
email: my_email@email.com
author: Barry Weiss

show_excerpts: true
page_excerpts: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
