version: '3.8'
services:
  jekyll:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/src/app
    environment:
      JEKYLL_ENV: development
    command: bundle exec jekyll serve --host 0.0.0.0 --livereload